name: Build & Deploy Sonic Inflation Bot

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    if: github.actor != 'web-flow'
    runs-on: self-hosted  # This runs on your Windows Server with GitHub runner installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish bot
      run: dotnet publish SonicInflatorService/SonicInflatorService.csproj -c Release -r win-x64 --self-contained -o publish

    - name: Substitute env vars in appsettings.template.json using PowerShell
      shell: pwsh
      run: |
        $content = Get-Content appsettings.template.json -Raw
        $content = $content -replace '\$\{(\w+)\}', { param($m) $env:$($m.Groups[1].Value) }
        $content | Set-Content publish/appsettings.json
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    - name: Run deploy script
      shell: pwsh
      run: ./deployment.ps1
