name: Build & Deploy Sonic Inflation Bot

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    if: github.actor != 'web-flow'
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK cleanly
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Override DOTNET_ROOT and fix PATH
      run: |
        echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
        echo "$HOME/.dotnet" >> $GITHUB_PATH
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
    - name: Confirm .NET install
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish bot
      run: dotnet publish SonicInflatorService/SonicInflatorService.csproj -c Release -r linux-x64 --self-contained -o publish

    - name: Inject secrets into appsettings.json
      shell: bash
      run: |
        envsubst < appsettings.template.json > publish/appsettings.json
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    - name: Run deploy script
      shell: bash
      run: ./deployment.sh
