name: Deploy to Windows Server

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    types: [ closed ]

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: './SonicInflatorService/SonicInflatorService.csproj'
  PUBLISH_PATH: './publish'
  SERVICE_NAME: 'SonicInflatorService'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Substitute Connection String in appsettings
      run: |
        # Replace placeholder with actual connection string
        sed -i 's|{{DATABASE_CONNECTION_STRING}}|${{ secrets.DATABASE_CONNECTION_STRING }}|g' ./SonicInflatorService/appsettings.json
        
        # Verify substitution worked (without exposing the secret)
        if grep -q "{{DATABASE_CONNECTION_STRING}}" ./SonicInflatorService/appsettings.json; then
          echo "❌ Connection string substitution failed"
          exit 1
        else
          echo "✅ Connection string substituted successfully"
        fi

    - name: Publish
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} \
          --configuration Release \
          --runtime win-x64 \
          --self-contained true \
          --output ${{ env.PUBLISH_PATH }} \
          /p:PublishSingleFile=true \
          /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ${{ env.PUBLISH_PATH }}
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ${{ env.PUBLISH_PATH }}
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.WINDOWS_SERVER_HOST }}
        username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        port: ${{ secrets.WINDOWS_SERVER_SSH_PORT }}
        timeout: 30s
        script: |
          Write-Host "SSH connection successful"
          Get-Date
          whoami
